theme: jekyll-theme-minimal
title: Markus Renoldner
description: Personal webpage
url: https://markusrenoldner.github.io/

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
